const { test } = require('node:test');
const assert = require('node:assert/strict');
const { LiveStore } = require('../araf-ops-src/live-store.js');
function mockDB(handler){
 const calls=[];return {calls,from(table){const op={table,filters:[]};calls.push(op);const q={};
  for(const name of ['select','order','range','eq','is','update','insert','maybeSingle','single'])q[name]=(...args)=>{if(['eq','is'].includes(name))op.filters.push([name,...args]);else op[name]=args;return q;};
  q.then=(resolve,reject)=>Promise.resolve().then(()=>handler(op)).then(resolve,reject);return q;
 },rpc:async(name,payload)=>{calls.push({rpc:name,payload});return handler({rpc:name,payload});}};
}
const admin={id:'e1',name:'Operator',role:'admin'};
function store(db){const s=new LiveStore(db,null,async()=>({ok:true,user:{id:'auth1'},admin:{active:true,employee_id:'e1',display_name:'Operator',role:'admin'}}));s.user=admin;return s;}
test('session is verified by existing API, not editable local storage',async()=>{const s=store(mockDB(()=>({})));assert.equal((await s.verify()).id,'e1');s.api=async()=>({ok:true,admin:{active:false},user:{id:'a'}});await assert.rejects(s.verify());});
test('loads every page beyond Supabase default cap',async()=>{const db=mockDB(op=>({data:Array.from({length:op.range[0]<1000?500:201},(_,i)=>({id:op.range[0]+i}))}));const rows=await store(db).all('service_requests');assert.equal(rows.length,1201);assert.deepEqual(db.calls.map(c=>c.range),[[0,499],[500,999],[1000,1499]]);});
test('employee scope uses the original assigned_to filter',async()=>{const db=mockDB(()=>({data:[]})),s=store(db);s.user={id:'e2',role:'employee'};await s.requests();assert.deepEqual(db.calls[0].filters,[['eq','assigned_to','e2']]);});
test('successful write uses original fields, existing version, then audit',async()=>{const db=mockDB(op=>op.table==='request_activity_log'?{}:{data:{id:'r1',updated_at:'new',status:'done'}}),s=store(db);s.rows.r1={id:'r1',updated_at:'old'};await s.patchRequest('r1',{status:'done',closed_by:'e1'});assert.deepEqual(db.calls[0].filters,[['eq','id','r1'],['eq','updated_at','old']]);assert.equal(s.rows.r1.status,'done');assert.equal(db.calls[1].table,'request_activity_log');});
test('RLS/permission error never updates the displayed store',async()=>{const db=mockDB(()=>({error:{message:'denied'}})),s=store(db);s.rows.r1={id:'r1',status:'new',updated_at:'old'};await assert.rejects(s.patchRequest('r1',{status:'done'}),/denied/);assert.equal(s.rows.r1.status,'new');assert.equal(db.calls.length,1);});
test('concurrent update returns conflict instead of overwriting notes',async()=>{const s=store(mockDB(()=>({data:null})));s.rows.r1={id:'r1',notes:[{text:'first'}],updated_at:'old'};await assert.rejects(s.addNote('r1','second'),/تغيّر/);assert.equal(s.rows.r1.notes.length,1);});
test('note preserves existing metadata and original notes contract',async()=>{const db=mockDB(op=>({data:{id:'r1',...op.update?.[0]}})),s=store(db);s.rows.r1={id:'r1',notes:[{by:'Old',text:'first',extra:true}],updated_at:'old'};await s.addNote('r1','second');const notes=db.calls[0].update[0].notes;assert.equal(notes[0].extra,true);assert.equal(notes[1].by_id,'e1');assert.equal(notes[1].by,'Operator');});
test('audit failure is reported separately after a successful save',async()=>{const s=store(mockDB(op=>op.table==='request_activity_log'?{error:{message:'audit failure'}}:{data:{id:'r1',status:'done'}}));s.rows.r1={updated_at:'old'};const r=await s.patchRequest('r1',{status:'done'});assert.ok(r.warning);assert.equal(s.rows.r1.status,'done');});
test('deletion uses the existing approval RPC and forbids self approval',async()=>{const db=mockDB(()=>({data:true})),s=store(db);await assert.rejects(s.approveDelete({request_id:'r1',status:'pending',requested_by:'e1'}));assert.equal(db.calls.length,0);await s.approveDelete({request_id:'r1',status:'pending',requested_by:'e2'});assert.equal(db.calls[0].rpc,'approve_and_delete_service_request');});
test('support conversion calls existing RPC and validates price',async()=>{const db=mockDB(()=>({data:'r1'})),s=store(db);await assert.rejects(s.convertTicket('t1','consultation','Consult',-1,'paid'));await s.convertTicket('t1','consultation','Consult',100,'paid');assert.equal(db.calls[0].rpc,'convert_support_ticket_to_request');assert.equal(db.calls[0].payload.p_converted_by,'e1');});
test('new rows keep database-generated request IDs',async()=>{const db=mockDB(op=>({data:{...op.insert[0],id:'server-id'}})),s=store(db);const row=await s.insert('service_requests',{customer_name:'Test'});assert.equal(row.id,'server-id');assert.equal(db.calls[0].insert[0].id,undefined);});
